window.CITIES = [
  {n:"Jakarta Pusat", z:"jabodetabek"},
  {n:"Jakarta Selatan", z:"jabodetabek"},
  {n:"Jakarta Barat", z:"jabodetabek"},
  {n:"Jakarta Timur", z:"jabodetabek"},
  {n:"Jakarta Utara", z:"jabodetabek"},
  {n:"Depok", z:"jabodetabek"},
  {n:"Tangerang", z:"jabodetabek"},
  {n:"Tangerang Selatan", z:"jabodetabek"},
  {n:"Bekasi", z:"jabodetabek"},
  {n:"Bogor", z:"jabodetabek"},
  {n:"Bandung", z:"jawa"},
  {n:"Cimahi", z:"jawa"},
  {n:"Tasikmalaya", z:"jawa"},
  {n:"Cirebon", z:"jawa"},
  {n:"Semarang", z:"jawa"},
  {n:"Solo / Surakarta", z:"jawa"},
  {n:"Yogyakarta", z:"jawa"},
  {n:"Purwokerto", z:"jawa"},
  {n:"Pekalongan", z:"jawa"},
  {n:"Tegal", z:"jawa"},
  {n:"Surabaya", z:"jawa"},
  {n:"Malang", z:"jawa"},
  {n:"Kediri", z:"jawa"},
  {n:"Sidoarjo", z:"jawa"},
  {n:"Gresik", z:"jawa"},
  {n:"Madiun", z:"jawa"},
  {n:"Denpasar", z:"bali"},
  {n:"Badung", z:"bali"},
  {n:"Gianyar", z:"bali"},
  {n:"Mataram", z:"bali"},
  {n:"Kupang", z:"bali"},
  {n:"Medan", z:"sumatra"},
  {n:"Binjai", z:"sumatra"},
  {n:"Padang", z:"sumatra"},
  {n:"Pekanbaru", z:"sumatra"},
  {n:"Batam", z:"sumatra"},
  {n:"Palembang", z:"sumatra"},
  {n:"Bandar Lampung", z:"sumatra"},
  {n:"Jambi", z:"sumatra"},
  {n:"Bengkulu", z:"sumatra"},
  {n:"Banda Aceh", z:"sumatra"},
  {n:"Pontianak", z:"kalimantan"},
  {n:"Banjarmasin", z:"kalimantan"},
  {n:"Balikpapan", z:"kalimantan"},
  {n:"Samarinda", z:"kalimantan"},
  {n:"Palangka Raya", z:"kalimantan"},
  {n:"Tarakan", z:"kalimantan"},
  {n:"Makassar", z:"sulawesi"},
  {n:"Manado", z:"sulawesi"},
  {n:"Palu", z:"sulawesi"},
  {n:"Kendari", z:"sulawesi"},
  {n:"Gorontalo", z:"sulawesi"},
  {n:"Ambon", z:"papua"},
  {n:"Ternate", z:"papua"},
  {n:"Jayapura", z:"papua"},
  {n:"Sorong", z:"papua"},
  {n:"Merauke", z:"papua"}
];

window.ONGKIR = {
  jabodetabek: { kg: 12000, etd: "1-2 hari", label: "Jabodetabek" },
  jawa: { kg: 18000, etd: "2-3 hari", label: "Jawa" },
  bali: { kg: 28000, etd: "3-4 hari", label: "Bali & Nusa Tenggara" },
  sumatra: { kg: 32000, etd: "3-5 hari", label: "Sumatra" },
  kalimantan: { kg: 42000, etd: "4-6 hari", label: "Kalimantan" },
  sulawesi: { kg: 45000, etd: "4-7 hari", label: "Sulawesi" },
  papua: { kg: 78000, etd: "5-10 hari", label: "Maluku & Papua" }
};
