window.PRODUCTS = [
  {id:0, cat:"vitamin", name:"Mega Vitamin D3K2", tag:"Vitamin tulang", manfaat:"D3 4.000 IU + K2 MK-7 70 mcg membantu penyerapan kalsium-fosfor, pembentukan tulang, dan mengarahkan kalsium ke tulang—bukan pembuluh darah.", dosis:"1 kapsul/hari bersama air, lebih baik dengan makanan berlemak. 90 kapsul ≈ 3 bulan.", img:"images/p00.jpg"},
  {id:1, cat:"ginseng", name:"Red Ginseng & Lespedeza", tag:"Kesehatan pria", manfaat:"Ginseng merah (stamina, imunitas, sirkulasi, memori) dipadu Lespedeza cuneata untuk dukungan andropause pria.", dosis:"1 sachet 3 g/hari, langsung atau dilarutkan air hangat.", img:"images/p01.jpg"},
  {id:2, cat:"vitamin", name:"Pro Packed-Tamin", tag:"21 vitamin & mineral", manfaat:"13 vitamin + 8 mineral, B-kompleks tinggi untuk energi, metabolisme, dan daya tahan harian.", dosis:"2 kapsul, 1× sehari saat makan. 120 kapsul ≈ 2 bulan.", img:"images/p02.jpg"},
  {id:3, cat:"imun", name:"Organic Fermented Noni", tag:"Superfood fermentasi", manfaat:"Noni organik Jawa difermentasi ±1.440 jam. Kaya fitokimia, asam amino, dan antioksidan untuk imunitas serta pencernaan.", dosis:"30 ml, 1–2× sehari (atau 1 pouch/hari). Kocok, boleh diencerkan. Kulkas setelah dibuka.", img:"images/p03.jpg"},
  {id:4, cat:"metabolik", name:"Blood Sugar Cut Bitter Melon", tag:"Pare / eyju", manfaat:"Ekstrak pare tradisional untuk membantu menjaga kadar gula darah sebagai bagian dari pola makan sehat.", dosis:"Ikuti label, biasanya 1 sachet/hari. Bukan pengganti obat diabetes.", img:"images/p04.jpg"},
  {id:5, cat:"metabolik", name:"Bellflower Pear & Quince", tag:"Tenggorokan", manfaat:"Ekstrak akar belbunga (doraji), pir, dan moqua untuk kenyamanan tenggorokan dan saluran napas.", dosis:"1 sachet/stick per hari, dapat diencerkan.", img:"images/p05.jpg"},
  {id:6, cat:"rambut", name:"Root Vital Hair Care Set", tag:"Rambut rontok", manfaat:"Rangkaian meredakan gejala rambut rontok dan menyehatkan kulit kepala.", dosis:"Sampo di rambut basah, pijat, bilas. Lanjut treatment. Rutin 8–12 minggu.", img:"images/p06.jpg"},
  {id:7, cat:"metabolik", name:"Slim Body Applehenon Jelly", tag:"Polifenol apel", manfaat:"Applephenon mendukung metabolisme bersama diet dan olahraga.", dosis:"1–2 stick jeli/hari. Bukan obat peluntur lemak.", img:"images/p07.jpg"},
  {id:8, cat:"cantik", name:"Pomegranate Beauty", tag:"Delima", manfaat:"Ekstrak delima sebagai antioksidan untuk kecerahan dan kecantikan dari dalam.", dosis:"Umumnya 2 sachet/hari.", img:"images/p08.jpg"},
  {id:9, cat:"vitamin", name:"Power Vita Energy", tag:"Stamina", manfaat:"Serbuk energi untuk membantu vitalitas aktivitas harian.", dosis:"1 sachet/hari dilarutkan air. Hindari malam jika mengganggu tidur.", img:"images/p09.jpg"},
  {id:10, cat:"vitamin", name:"Vital Mega Vitamin C", tag:"Vitamin C 2000", manfaat:"Membantu imunitas, kolagen, kesehatan kulit, dan antioksidan.", dosis:"1 sachet/hari dilarutkan air, setelah makan.", img:"images/p10.jpg"},
  {id:11, cat:"vitamin", name:"Vital Color Vitamin C", tag:"Colorfood", manfaat:"Vitamin C dari konsep buah-sayur berwarna untuk imunitas dan kecerahan.", dosis:"1 sachet/hari, larutkan, minum segera.", img:"images/p11.jpg"},
  {id:12, cat:"metabolik", name:"Finezyme", tag:"Enzim nanas", manfaat:"Enzim bromelain + B1, asam pantotenat, biotin membantu metabolisme zat gizi.", dosis:"1 sachet/hari, lebih nyaman setelah makan.", img:"images/p12.jpg"},
  {id:13, cat:"metabolik", name:"Slim Body Puer Tea", tag:"Teh puerh", manfaat:"Teh puer untuk rasa ringan dan dukungan metabolisme.", dosis:"1 sachet diseduh air panas, 1× sehari.", img:"images/p13.jpg"},
  {id:14, cat:"imun", name:"Probiotics 10+", tag:"10 strain", manfaat:"Menjaga flora usus, pencernaan, dan daya tahan dari saluran cerna.", dosis:"1 sachet/hari dengan air suhu ruang. Jangan air panas.", img:"images/p14.jpg"},
  {id:15, cat:"imun", name:"SCI Microbiome", tag:"Mikrobioma", manfaat:"Mendukung keseimbangan mikrobiota usus.", dosis:"1 sachet/hari, campur air dingin.", img:"images/p15.jpg"},
  {id:16, cat:"khusus", name:"Iron", tag:"Zat besi", manfaat:"Membantu pembentukan sel darah merah. Penting bagi wanita usia subur.", dosis:"1 sachet/hari. Hindari bersamaan teh/kopi/susu.", img:"images/p16.jpg"},
  {id:17, cat:"imun", name:"HemoHIM", tag:"Imunitas unggulan", manfaat:"Ramuan Angelica, Cnidium, dan Paeonia. Membantu memelihara daya tahan dan energi.", dosis:"Dewasa 1 sachet 2× sehari. Anak ≥6 th 1 sachet/hari. Tidak untuk anak <6 th.", img:"images/p17.jpg"},
  {id:18, cat:"imun", name:"Pure Spirulina", tag:"Superfood", manfaat:"Protein nabati, klorofil, zat besi, dan antioksidan.", dosis:"Beberapa tablet/hari sesuai label, setelah makan.", img:"images/p18.jpg"},
  {id:19, cat:"metabolik", name:"Psyllium Husk", tag:"Serat", manfaat:"Serat kulit plantago untuk kelancaran BAB dan dukungan kolesterol.", dosis:"1 sachet, 2–3× sehari WAJIB dengan banyak air.", img:"images/p19.jpg"},
  {id:20, cat:"imun", name:"Green Propolis Gummies", tag:"Propolis", manfaat:"Propolis hijau dalam gummy untuk dukungan imunitas.", dosis:"1–2 gummy/hari sesuai kemasan.", img:"images/p20.jpg"},
  {id:21, cat:"imun", name:"Green Propolis Spray", tag:"Semprot tenggorokan", manfaat:"Menjaga kebersihan rongga mulut dan kenyamanan tenggorokan.", dosis:"Semprot 1–2 kali, beberapa kali sehari.", img:"images/p21.jpg"},
  {id:22, cat:"cantik", name:"Inner Collagen", tag:"Kolagen minum", manfaat:"Peptida kolagen ikan ±3.270 mg + HA, elastin, ceramide, vitamin C untuk elastisitas kulit.", dosis:"1 botol 25 ml/hari, lebih baik di antara waktu makan. Enak dingin.", img:"images/p22.jpg"},
  {id:23, cat:"khusus", name:"Rhubarb Queen", tag:"Menopause", manfaat:"Rhaponticin dari akar rhubarb membantu meredakan gejala menopause + vitamin E & K.", dosis:"1 kapsul/hari. Kursus 8–12 minggu.", img:"images/p23.jpg"},
  {id:24, cat:"khusus", name:"W Inner Balance", tag:"Kewanitaan", manfaat:"Membantu keseimbangan flora kewanitaan dari dalam.", dosis:"1 porsi/hari sesuai label.", img:"images/p24.jpg"},
  {id:25, cat:"khusus", name:"Sophora Queen", tag:"Kesehatan wanita", manfaat:"Formulasi herbal untuk kenyamanan siklus dan kesehatan wanita.", dosis:"Ikuti kemasan, umumnya 1 porsi/hari.", img:"images/p25.jpg"},
  {id:26, cat:"khusus", name:"Saw Palmetto", tag:"Pria / prostat", manfaat:"Saw palmetto tradisional untuk kesehatan prostat dan saluran kemih pria dewasa.", dosis:"1–2 kapsul/hari setelah makan. Konsultasi urolog jika ada keluhan.", img:"images/p26.jpg"},
  {id:27, cat:"tulang", name:"Eye Lutein", tag:"Kesehatan mata", manfaat:"Lutein marigold menjaga mata dari paparan layar dan cahaya biru.", dosis:"1 kapsul/hari setelah makan.", img:"images/p27.jpg"},
  {id:28, cat:"tulang", name:"Eye Health Luaxanthin", tag:"Lutein + zeaxanthin", manfaat:"Kombinasi lutein-zeaxanthin untuk makula dan penglihatan.", dosis:"1 kapsul/hari bersama makanan berlemak.", img:"images/p28.jpg"},
  {id:29, cat:"ginseng", name:"Quantum Energy Stick", tag:"Energi", manfaat:"Stick praktis untuk dukungan energi harian.", dosis:"1 stick/hari sesuai kemasan.", img:"images/p29.jpg"},
  {id:30, cat:"ginseng", name:"Red Ginseng Granule", tag:"Hongsamdan", manfaat:"100% ginseng merah Korea, ginsenoside tinggi untuk stamina dan imunitas.", dosis:"Dewasa 1 sachet/hari; <18 tahun ½ sachet.", img:"images/p30.jpg"},
  {id:31, cat:"ginseng", name:"Red Ginseng Extract Stick", tag:"Ekstrak cair", manfaat:"Ekstrak ginseng merah siap minum.", dosis:"1 stick/hari.", img:"images/p31.jpg"},
  {id:32, cat:"ginseng", name:"Red Ginseng Jelly Stick", tag:"Jeli ginseng", manfaat:"Ginseng merah rasa lebih ramah, mudah dikonsumsi.", dosis:"1 stick jeli/hari.", img:"images/p32.jpg"},
  {id:33, cat:"metabolik", name:"Glucose Care Banaba", tag:"Daun banaba", manfaat:"Banaba (corosolic acid) mendukung metabolisme glukosa.", dosis:"Ikuti kemasan. Tetap jaga diet.", img:"images/p33.jpg"},
  {id:34, cat:"omega", name:"rTG Omega-3", tag:"Minyak ikan", manfaat:"EPA+DHA bentuk rTG mudah diserap untuk jantung, otak, mata, dan trigliserida.", dosis:"1–2 kapsul/hari setelah makan.", img:"images/p34.jpg"},
  {id:35, cat:"omega", name:"Vegan Algae rTG Omega-3", tag:"Nabati / vegan", manfaat:"Omega-3 dari mikroalga. EPA+DHA 600 mg/2 kapsul + vitamin A & E.", dosis:"2 kapsul/hari setelah makan.", img:"images/p35.jpg"},
  {id:36, cat:"omega", name:"Alaska E-Omega 3", tag:"Ikan Alaska", manfaat:"Omega-3 perairan dingin + vitamin E pelindung minyak.", dosis:"Umumnya 2 kapsul/hari setelah makan.", img:"images/p36.jpg"},
  {id:37, cat:"tulang", name:"Rhodiola Milk Thistle", tag:"Adaptogen & hati", manfaat:"Rhodiola untuk stres; milk thistle mendukung fungsi hati.", dosis:"Ikuti label. Konsultasi jika ada penyakit hati.", img:"images/p37.jpg"},
  {id:38, cat:"khusus", name:"Smart Memory Up", tag:"Memori", manfaat:"Membantu menjaga fungsi kognitif dan daya ingat.", dosis:"1× sehari, biasanya pagi.", img:"images/p38.jpg"},
  {id:39, cat:"khusus", name:"Good Sleep Lactium", tag:"Tidur", manfaat:"Lactium membantu relaksasi dan kualitas tidur.", dosis:"1 porsi 30–60 menit sebelum tidur.", img:"images/p39.jpg"},
  {id:40, cat:"tulang", name:"Turmacin MSM", tag:"Sendi", manfaat:"Ekstrak kunyit + MSM untuk kenyamanan sendi.", dosis:"1–2 tablet/hari setelah makan.", img:"images/p40.jpg"},
  {id:41, cat:"vitamin", name:"Vital Color Food Multivitamin", tag:"Harian", manfaat:"Multivitamin konsep color food untuk asupan dasar dan antioksidan.", dosis:"1 porsi/hari setelah makan.", img:"images/p41.jpg"},
  {id:42, cat:"tulang", name:"Tri-Active Cal Mag D", tag:"Tulang", manfaat:"Kalsium + magnesium + vitamin D untuk tulang dan gigi.", dosis:"1–2 tablet/hari setelah makan.", img:"images/p42.jpg"},
  {id:43, cat:"tulang", name:"Chewable Calcium", tag:"Kalsium kunyah", manfaat:"Kalsium praktis dikunyah untuk asupan harian.", dosis:"Kunyah sesuai jumlah di label, setelah makan.", img:"images/p43.jpg"},
  {id:44, cat:"khusus", name:"Ginkgo and Natto", tag:"Sirkulasi", manfaat:"Ginkgo untuk sirkulasi serebral; natto terkait aliran darah.", dosis:"Ikuti label. Hati-hati jika memakai pengencer darah.", img:"images/p44.jpg"},
  {id:45, cat:"vitamin", name:"Blooming Biotin", tag:"Rambut & kuku", manfaat:"Biotin mendukung metabolisme serta kesehatan rambut, kulit, dan kuku.", dosis:"1 tablet/hari. Hasil setelah pemakaian teratur.", img:"images/p45.jpg"},
  {id:46, cat:"vitamin", name:"Vitamin B Complex", tag:"Energi", manfaat:"Metabolisme energi, saraf, dan pembentukan sel darah merah.", dosis:"1 tablet/hari setelah makan.", img:"images/p46.jpg"},
  {id:47, cat:"metabolik", name:"Stomach Health Daily Care", tag:"Lambung", manfaat:"Membantu menjaga kesehatan lambung dan saluran cerna atas.", dosis:"Ikuti kemasan, sering sebelum makan.", img:"images/p47.jpg"},
  {id:48, cat:"metabolik", name:"Triple Up Protein", tag:"Protein", manfaat:"Bubuk protein 3 sumber untuk otot, kenyang, dan gizi harian.", dosis:"1 sachet dilarutkan air/susu, setelah olahraga atau selingan.", img:"images/p48.jpg"},
  {id:49, cat:"anak", name:"Kids Vegan Gummy Multivitamin", tag:"Anak", manfaat:"8 vitamin + 3 mineral rasa buah, vegan.", dosis:"2 gummy/hari. Hanya untuk anak yang sudah bisa mengunyah aman.", img:"images/p49.jpg"},
  {id:50, cat:"anak", name:"Kids Chewable Omega-3", tag:"Anak", manfaat:"EPA/DHA untuk perkembangan otak dan penglihatan.", dosis:"Kunyah sesuai usia di label, setelah makan.", img:"images/p50.jpg"},
  {id:51, cat:"anak", name:"Kids Red Ginseng", tag:"Anak", manfaat:"Ginseng merah dosis anak untuk daya tahan dan konsentrasi.", dosis:"1 stick/hari.", img:"images/p51.jpg"},
  {id:52, cat:"anak", name:"Kids Probiotics", tag:"Anak", manfaat:"Flora usus anak, berguna setelah antibiotik.", dosis:"1 sachet/hari dicampur air dingin.", img:"images/p52.jpg"},
  {id:53, cat:"lain", name:"Outdoor Patch", tag:"Patch", manfaat:"Patch luar ruangan sesuai jenis isi kemasan.", dosis:"Tempel di pakaian/kulit sesuai petunjuk. Jangan pada luka.", img:"images/p53.jpg"},
  {id:54, cat:"skincare", name:"Absolute Reset Balm", tag:"CellActive", manfaat:"Balm multifungsi menenangkan dan melembapkan area kering.", dosis:"Oles tipis di bibir/area kering, pagi atau malam.", img:"images/p54.jpg"},
  {id:55, cat:"skincare", name:"Absolute CellActive Toner", tag:"Anti-aging", manfaat:"Membersihkan sisa kotoran, mencerahkan, menyiapkan kulit.", dosis:"Setelah cuci muka, usap wajah & leher.", img:"images/p55.jpg"},
  {id:56, cat:"skincare", name:"Absolute CellActive Ampoule", tag:"De-aging", manfaat:"Ampul kental: cerah, kencang, garis halus.", dosis:"Tetes di telapak, ratakan wajah-leher, tepuk. Hindari mata.", img:"images/p56.jpg"},
  {id:57, cat:"skincare", name:"Absolute CellActive Serum", tag:"Kencang", manfaat:"Meningkatkan densitas dan elastisitas kulit.", dosis:"2–3 tetes setelah ampoule, usap ke atas.", img:"images/p57.jpg"},
  {id:58, cat:"skincare", name:"Absolute CellActive Lotion", tag:"Barrier", manfaat:"Menyeimbangkan minyak-air di permukaan kulit.", dosis:"Seujung jari, ratakan setelah serum.", img:"images/p58.jpg"},
  {id:59, cat:"skincare", name:"Absolute CellActive Eye Complex", tag:"Area mata", manfaat:"Mencerahkan dan menyamarkan garis halus sekitar mata.", dosis:"Titik kecil di tulang mata, tap-tap, jangan tarik kulit.", img:"images/p59.jpg"},
  {id:60, cat:"skincare", name:"Absolute CellActive Nutrition Cream", tag:"Pelembap", manfaat:"Krim nutrisi mengunci kelembapan dan memberi glow.", dosis:"Langkah terakhir, tipis merata termasuk leher.", img:"images/p60.jpg"},
  {id:61, cat:"skincare", name:"Absolute CellActive Set", tag:"Paket 6 langkah", manfaat:"Rangkaian klinik anti-aging lengkap dari toner hingga krim.", dosis:"Pakai berurutan pagi/malam. Pagi akhiri sunscreen.", img:"images/p61.jpg"},
  {id:62, cat:"skincare", name:"Absolute Snow Toner", tag:"Mencerahkan", manfaat:"Toner rangkaian Snow untuk kulit kusam dan noda.", dosis:"Usap setelah cuci muka, pagi-malam.", img:"images/p62.jpg"},
  {id:63, cat:"skincare", name:"Absolute Snow Serum", tag:"Noda hitam", manfaat:"Serum pencerah dan perata warna.", dosis:"2–3 tetes setelah toner.", img:"images/p63.jpg"},
  {id:64, cat:"skincare", name:"Absolute Snow Day Cream", tag:"Siang", manfaat:"Pelembap siang mencerahkan.", dosis:"Pagi, lalu lanjutkan sunscreen.", img:"images/p64.jpg"},
  {id:65, cat:"skincare", name:"Absolute Snow Night Cream", tag:"Malam", manfaat:"Perawatan malam untuk kecerahan.", dosis:"Malam sebagai langkah terakhir.", img:"images/p65.jpg"},
  {id:66, cat:"skincare", name:"Snow Tone-Up Essence Sun", tag:"Sunscreen", manfaat:"Essence + proteksi UV + efek tone-up.", dosis:"Langkah terakhir pagi, ulangi jika terpapar lama.", img:"images/p66.jpg"},
  {id:67, cat:"skincare", name:"Snow Dark Spot Corrector", tag:"Spot", manfaat:"Menargetkan noda hitam dan bekas.", dosis:"Titikkan tipis pada noda, pagi-malam.", img:"images/p67.jpg"},
  {id:68, cat:"skincare", name:"Absolute Snow Facial Mask", tag:"Masker", manfaat:"Masker mencerahkan dan melembapkan.", dosis:"1–2× seminggu, 10–20 menit.", img:"images/p68.jpg"},
  {id:69, cat:"skincare", name:"Absolute Snow Set", tag:"Paket cerah", manfaat:"Rangkaian Snow 5 pcs untuk program pencerahan.", dosis:"Ikuti urutan dalam kotak, pagi-malam.", img:"images/p69.jpg"},
  {id:70, cat:"skincare", name:"THE FAME Toner", tag:"Glowing", manfaat:"Melembapkan dan menenangkan langkah pertama The Fame.", dosis:"Usap merata setelah cuci muka.", img:"images/p70.jpg"},
  {id:71, cat:"skincare", name:"THE FAME Eye Cream", tag:"Mata", manfaat:"Nutrisi area mata dan garis halus.", dosis:"Tap-tap di tulang mata, pagi-malam.", img:"images/p71.jpg"},
  {id:72, cat:"skincare", name:"THE FAME Essence", tag:"Konsentrat", manfaat:"Essence nutrisi tinggi, ikon rangkaian The Fame.", dosis:"Setelah toner & eye cream, ratakan hingga meresap.", img:"images/p72.jpg"},
  {id:73, cat:"skincare", name:"THE FAME Lotion", tag:"Seimbang", manfaat:"Menyeimbangkan minyak dan air.", dosis:"Setelah essence, usap ke atas.", img:"images/p73.jpg"},
  {id:74, cat:"skincare", name:"THE FAME Nutrition Cream", tag:"Krim", manfaat:"Mengunci lembap dan membantu kecerahan.", dosis:"Langkah terakhir malam/pagi.", img:"images/p74.jpg"},
  {id:75, cat:"skincare", name:"THE FAME Set 5 pcs", tag:"Paket", manfaat:"Sistem 5 langkah kulit lembap dan cerah.", dosis:"Toner → eye cream → essence → lotion → cream.", img:"images/p75.jpg"},
  {id:76, cat:"skincare", name:"Derma Real Cica Toner", tag:"Sensitif", manfaat:"Centella menenangkan kulit iritasi.", dosis:"Usap lembut setelah cuci muka.", img:"images/p76.jpg"},
  {id:77, cat:"skincare", name:"Derma Real Cica Ampoule", tag:"Barrier", manfaat:"Ampul cica memperbaiki barrier yang terganggu.", dosis:"Teteskan, tepuk hingga meresap.", img:"images/p77.jpg"},
  {id:78, cat:"skincare", name:"Derma Real Cica Cream", tag:"Tenang", manfaat:"Krim menenangkan kemerahan.", dosis:"Langkah terakhir, tipis merata.", img:"images/p78.jpg"},
  {id:79, cat:"skincare", name:"Derma Real Cica Set", tag:"Paket 3 pcs", manfaat:"Rangkaian cica ringkas untuk kulit sensitif.", dosis:"Toner → ampoule → cream.", img:"images/p79.jpg"},
  {id:80, cat:"skincare", name:"Derma Real Cica Gel Cleanser", tag:"Pembersih", manfaat:"Membersihkan tanpa menggesek barrier.", dosis:"Busakan, usap, bilas air hangat.", img:"images/p80.jpg"},
  {id:81, cat:"skincare", name:"Hydra Brightening Set", tag:"Lembap + cerah", manfaat:"Paket hidrasi untuk kulit kering/kusam.", dosis:"Pakai berurutan pagi-malam.", img:"images/p81.jpg"},
  {id:82, cat:"skincare", name:"Hydra Brightening Toner", tag:"Hydra", manfaat:"Toner pelembap mencerahkan.", dosis:"Usap atau tepuk setelah cuci muka.", img:"images/p82.jpg"},
  {id:83, cat:"skincare", name:"Hydra Brightening Cream", tag:"Hydra", manfaat:"Krim melembapkan dan memberi cahaya.", dosis:"Setelah toner, ratakan.", img:"images/p83.jpg"},
  {id:84, cat:"skincare", name:"Acne Clear Set", tag:"Jerawat", manfaat:"4 langkah membersihkan sebum dan menenangkan jerawat.", dosis:"Cleanser → toner → serum; spot hanya di lesi.", img:"images/p84.jpg"},
  {id:85, cat:"skincare", name:"Acne Clear Foam Cleanser", tag:"Jerawat", manfaat:"Busa membersihkan pori dan sebum.", dosis:"Pagi-malam, bilas tuntas.", img:"images/p85.jpg"},
  {id:86, cat:"skincare", name:"Acne Clear Toner", tag:"Jerawat", manfaat:"Menyeimbangkan setelah cuci muka.", dosis:"Usap dengan kapas atau tangan.", img:"images/p86.jpg"},
  {id:87, cat:"skincare", name:"Acne Clear Spot Solution", tag:"Spot", manfaat:"Perawatan titik pada lesi jerawat.", dosis:"Oles tipis hanya di jerawat, malam hari.", img:"images/p87.jpg"},
  {id:88, cat:"skincare", name:"Acne Clear Serum", tag:"Jerawat", manfaat:"Serum meratakan tekstur dan menenangkan.", dosis:"Setelah toner, hindari area luka terbuka.", img:"images/p88.jpg"},
  {id:89, cat:"skincare", name:"Homme Skin Care", tag:"Pria", manfaat:"Perawatan ringkas pria pasca cukur.", dosis:"Setelah cuci muka, ikuti urutan set.", img:"images/p89.jpg"},
  {id:90, cat:"skincare", name:"Homme Toner", tag:"Pria", manfaat:"Menyegarkan dan menenangkan kulit pria.", dosis:"Usap setelah mencuci wajah.", img:"images/p90.jpg"},
  {id:91, cat:"skincare", name:"Homme Essence", tag:"Pria", manfaat:"Essence melembapkan tanpa rasa berat.", dosis:"Setelah toner, tepuk hingga meresap.", img:"images/p91.jpg"},
  {id:92, cat:"skincare", name:"Homme All-in-One Dry Skin", tag:"Pria", manfaat:"Satu produk untuk kulit kering pria.", dosis:"Setelah cuci muka, ratakan seluruh wajah.", img:"images/p92.jpg"},
  {id:93, cat:"skincare", name:"Homme All-in-One Oily Skin", tag:"Pria", manfaat:"All-in-one khusus kulit berminyak.", dosis:"Tipis merata setelah cuci muka.", img:"images/p93.jpg"},
  {id:94, cat:"skincare", name:"Hinoki Clay Mask", tag:"Masker", manfaat:"Masker tanah liat hinoki untuk pori dan sebum.", dosis:"Oles, diamkan sesuai label, bilas.", img:"images/p94.jpg"},
  {id:95, cat:"skincare", name:"Hinoki Clay Refill", tag:"Refill", manfaat:"Isi ulang masker hinoki, lebih hemat kemasan.", dosis:"Pasang cup refill ke wadah, kencangkan.", img:"images/p95.jpg"},
  {id:96, cat:"skincare", name:"Absolute French Rose Mask", tag:"Mask Series", manfaat:"Masker French Rose untuk melembapkan dan menenangkan.", dosis:"Oles merata, diamkan, angkat sisa.", img:"images/p96.jpg"},
  {id:97, cat:"skincare", name:"French Rose Refill", tag:"Refill", manfaat:"Cup isi ulang masker mawar.", dosis:"Ganti refill ke jar kaca.", img:"images/p97.jpg"},
  {id:98, cat:"skincare", name:"Absolute Mask Series", tag:"Masker", manfaat:"Masker perawatan intensif Absolute.", dosis:"1–2× seminggu malam hari.", img:"images/p98.jpg"},
  {id:99, cat:"skincare", name:"Honey Ginseng Mask", tag:"Masker", manfaat:"Madu + ginseng untuk nutrisi dan glow.", dosis:"Oles, diamkan, bersihkan.", img:"images/p99.jpg"},
  {id:100, cat:"skincare", name:"Honey Ginseng Refill", tag:"Refill", manfaat:"Isi ulang Honey Ginseng Mask.", dosis:"Pasang ke wadah asli.", img:"images/p100.jpg"},
  {id:101, cat:"skincare", name:"Honey Ginseng Mask Jar", tag:"Masker", manfaat:"Versi toples lengkap masker ginseng madu.", dosis:"Gunakan sendok/spatula bersih.", img:"images/p101.jpg"},
  {id:102, cat:"lain", name:"Atomy Sonic Toothbrush", tag:"Oral care", manfaat:"Sikat gigi sonik untuk kebersihan mulut.", dosis:"2× sehari, 2 menit, tekanan lembut.", img:"images/p102.jpg"},
  {id:103, cat:"skincare", name:"Synergy Ampoule Program", tag:"Ampul", manfaat:"Set ampul berwarna untuk program intensif kulit.", dosis:"Ikuti urutan warna/hari di booklet set.", img:"images/p103.jpg"},
  {id:104, cat:"skincare", name:"Beauty Device / Applicator", tag:"Alat", manfaat:"Alat bantu penyerapan skincare.", dosis:"Gunakan di kulit bersih sesuai manual.", img:"images/p104.jpg"},
  {id:105, cat:"skincare", name:"Peeling Pad", tag:"Eksfoliasi", manfaat:"Pad mengangkat sel kulit mati.", dosis:"1× sehari atau selang sehari, malam. Lanjut pelembap.", img:"images/p105.jpg"},
  {id:106, cat:"skincare", name:"Cleansing & Pad Set", tag:"Bersih", manfaat:"Perlengkapan pembersihan wajah harian.", dosis:"Pakai malam untuk angkat makeup/kotoran.", img:"images/p106.jpg"},
  {id:107, cat:"skincare", name:"Absolute Oil Serum Mist", tag:"Mist", manfaat:"Mist oil-serum dua fase melembapkan.", dosis:"Kocok, semprot 20 cm dari wajah, tepuk.", img:"images/p107.jpg"},
  {id:108, cat:"makeup", name:"Adelica Cushion Set", tag:"Makeup", manfaat:"Cushion coverage dengan bahan skincare.", dosis:"Tap dari tengah wajah ke luar.", img:"images/p108.jpg"},
  {id:109, cat:"makeup", name:"Adelica Foundation / Base", tag:"Makeup", manfaat:"Alas bedak cair meratakan warna kulit.", dosis:"Usap tipis dengan spons atau kuas.", img:"images/p109.jpg"},
  {id:110, cat:"makeup", name:"Adelica Cushion Compact", tag:"Makeup", manfaat:"Cushion praktis refill, hasil natural.", dosis:"Build tipis-tipis. Lepas makeup malam hari.", img:"images/p110.jpg"},
  {id:111, cat:"makeup", name:"Adelica Matt Cover Rosé Vanilla", tag:"Cushion", manfaat:"Finish matte shade Rosé Vanilla.", dosis:"Tap pada area yang perlu coverage.", img:"images/p111.jpg"},
  {id:112, cat:"makeup", name:"Adelica Cushion Open", tag:"Makeup", manfaat:"Cushion dengan cushion puff.", dosis:"Gunakan puff kering, tekan jangan gesek kasar.", img:"images/p112.jpg"},
  {id:113, cat:"makeup", name:"Adelica Pact / Powder", tag:"Makeup", manfaat:"Bedak padat mengunci makeup.", dosis:"Tekan tipis di T-zone.", img:"images/p113.jpg"},
  {id:114, cat:"makeup", name:"Lip Treatment", tag:"Bibir", manfaat:"Perawatan melembapkan bibir.", dosis:"Oles sebelum tidur atau sebagai base lipstik.", img:"images/p114.jpg"},
  {id:115, cat:"makeup", name:"Adelica Cream / Balm", tag:"Makeup", manfaat:"Krim/balm finishing makeup.", dosis:"Tipis di area yang kering.", img:"images/p115.jpg"},
  {id:116, cat:"makeup", name:"Brow Pencil", tag:"Alis", manfaat:"Pensil alis dual ujung + sikat.", dosis:"Gambar short strokes mengikuti arah rambut.", img:"images/p116.jpg"},
  {id:117, cat:"makeup", name:"Eyeliner Set", tag:"Mata", manfaat:"Eyeliner cair presisi.", dosis:"Gambar rapat di pangkal bulu mata.", img:"images/p117.jpg"},
  {id:118, cat:"makeup", name:"Adelica Lipstick", tag:"Bibir", manfaat:"Lipstik cream dengan warna buildup.", dosis:"Dari tengah bibir ke sudut.", img:"images/p118.jpg"},
  {id:119, cat:"makeup", name:"Adelica Gloss Tint", tag:"Bibir", manfaat:"Gloss tint basah memberi volume visual.", dosis:"Satu layer atau di atas lipstik.", img:"images/p119.jpg"},
  {id:120, cat:"makeup", name:"Adelica Gloss Tint Swatch", tag:"Bibir", manfaat:"Tint gloss warna persik.", dosis:"Aplikasi ulang sesuai kebutuhan.", img:"images/p120.jpg"},
  {id:121, cat:"makeup", name:"Lip Glow Merah", tag:"Bibir", manfaat:"Pelembap berwarna merah cerah.", dosis:"Oles merata, boleh di-blot.", img:"images/p121.jpg"},
  {id:122, cat:"makeup", name:"Adelica Lipstick Nude", tag:"Bibir", manfaat:"Warna nude-rose sehari-hari.", dosis:"Langsung atau dengan kuas lip.", img:"images/p122.jpg"},
  {id:123, cat:"makeup", name:"Lip Glow Coral", tag:"Bibir", manfaat:"Pelembap berwarna coral.", dosis:"Oles 1–2 layer.", img:"images/p123.jpg"},
  {id:124, cat:"rambut", name:"Hair Treatment Cream", tag:"Rambut", manfaat:"Treatment menutrisi batang rambut rusak.", dosis:"Setelah keramas, oles batang, diamkan, bilas.", img:"images/p124.jpg"},
  {id:125, cat:"rambut", name:"Bubble Hair / Foam Care", tag:"Rambut", manfaat:"Perawatan busa lembut untuk rambut.", dosis:"Busakan di rambut basah, pijat, bilas.", img:"images/p125.jpg"},
  {id:126, cat:"rambut", name:"Salon Intensive Treatment", tag:"Rambut", manfaat:"Perawatan intensif ujung dan batang.", dosis:"Fokus pada area rusak, bilas hingga bersih.", img:"images/p126.jpg"},
  {id:127, cat:"rambut", name:"Bubble Hair Color", tag:"Pewarna", manfaat:"Pewarnaan rambut rumahan jenis bubble.", dosis:"Tes alergi 48 jam. Ikuti waktu di booklet.", img:"images/p127.jpg"},
  {id:128, cat:"rambut", name:"Salon & Color", tag:"Pewarna", manfaat:"Kit pewarnaan setara salon.", dosis:"Sarung tangan, aduk, oles, tunggu, bilas tuntas.", img:"images/p128.jpg"},
  {id:129, cat:"rambut", name:"Salon & Color Kit", tag:"Pewarna", manfaat:"Set lengkap kuas dan formula warna.", dosis:"Jangan di kulit luka. Ikuti waktu proses.", img:"images/p129.jpg"},
  {id:130, cat:"rambut", name:"Hair Vital Shampoo", tag:"Sampo", manfaat:"Sampo menutrisi dan merawat rambut rontok/lemah.", dosis:"Pijat kulit kepala, bilas.", img:"images/p130.jpg"},
  {id:131, cat:"rambut", name:"Hair Vital Treatment", tag:"Treatment", manfaat:"Masker/treatment batang rambut.", dosis:"Setelah sampo, diamkan beberapa menit, bilas.", img:"images/p131.jpg"},
  {id:132, cat:"rambut", name:"Hair Vital Serum / Tonic", tag:"Kulit kepala", manfaat:"Serum/tonik kulit kepala.", dosis:"Teteskan di partingan, pijat, jangan bilas.", img:"images/p132.jpg"}
];

window.CATS = [
  {id:"all", label:"Semua"},
  {id:"vitamin", label:"Vitamin"},
  {id:"imun", label:"Imunitas"},
  {id:"ginseng", label:"Ginseng"},
  {id:"omega", label:"Omega-3"},
  {id:"metabolik", label:"Metabolisme"},
  {id:"tulang", label:"Tulang & Mata"},
  {id:"khusus", label:"Pria & Wanita"},
  {id:"cantik", label:"Beauty Drink"},
  {id:"anak", label:"Anak"},
  {id:"skincare", label:"Skincare"},
  {id:"makeup", label:"Makeup"},
  {id:"rambut", label:"Rambut"},
  {id:"lain", label:"Lainnya"}
];
